{{ if and .Values.galaxy.admin.email (and .Values.galaxy.admin.password .Values.galaxy.admin.api_key) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "galaxy.fullname" . }}-admin-user
  labels:
    app: {{ template "galaxy.name" . }}
    chart: {{ template "galaxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
     "helm.sh/hook": pre-install
data:
  email: {{ quote .Values.galaxy.admin.email }}
  user: {{ quote .Values.galaxy.admin.username }}
{{ end }}
