{{ if and .Values.admin.email (and .Values.admin.password .Values.admin.api_key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "galaxy.fullname" . }}-admin-secret
  labels:
    app: {{ template "galaxy.name" . }}
    chart: {{ template "galaxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ b64enc .Values.admin.password }}
  api-key: {{ b64enc .Values.admin.api_key }}
  database_password: {{ b64enc .Values.postgresql.postgresPassword }}
{{ end }}
