{{ if .Values.persistence.minikube.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: galaxy-pv
  labels:
    app: {{ template "galaxy.name" . }}
    chart: {{ template "galaxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
          path: "{{ .Values.persistence.minikube.hostPath }}"
{{ end }}
