apiVersion: v1
kind: Service
metadata:
  name: {{ template "galaxy.fullname" . }}-proftpd-svc
  labels:
    app: {{ template "galaxy.name" . }}-proftpd
    chart: {{ template "galaxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.proftpd.service.type }}
  ports:
    - port: {{ .Values.proftpd.service.port }}
      targetPort: 22
      protocol: TCP
      name: sftp
  selector:
    app: {{ template "galaxy.name" . }}-proftpd
    release: {{ .Release.Name }}