apiVersion: v1
kind: Service
metadata:
  name: {{ template "galaxy.fullname" . }}
  labels:
    app: {{ template "galaxy.name" . }}
    chart: {{ template "galaxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.node_port_exposed }}
      nodePort: {{ .Values.service.node_port_exposed }}
      {{- end }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ template "galaxy.name" . }}
    release: {{ .Release.Name }}