kind: PersistentVolume
apiVersion: v1
metadata:
  name: docker-pv-volume1
  labels:
    type: local
  annotations:
    pv.beta.kubernetes.io/gid: "0"
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/run/docker.sock"
