apiVersion: v1
kind: Pod
metadata:
  name: galaxy-postgres
spec:

  volumes:
  - name: shared-data
    persistentVolumeClaim:
     claimName: shared-data
     
  - persistentVolumeClaim:
     claimName: dockersocket
    name: dockersocket
  
 
  containers:

  

  - name: galaxy-postgres
    image: abhikghosh41/galaxy-postgres
    volumeMounts:
    - name: shared-data
      mountPath: /var/lib/postgresql/
    
    ports:
    - hostPort: 5432
      containerPort: 5432
      containerPort: 80
    
    resources: {}
    
    env:
    - name: POSTGRES_PASSWORD
      value: chaopagoosaequuashie
    - name: POSTGRES_USER
      value: galaxy
    - name: POSTGRES_DB
      value: galaxy
  
  
  