apiVersion: v1
kind: Pod
metadata:
  name: galaxy-init
spec:

  volumes:
  - name: shared-data
    persistentVolumeClaim:
     claimName: shared-data
     
  - persistentVolumeClaim:
     claimName: dockersocket
    name: dockersocket
  containers:
    
  - name: galaxy-init
    image: abhikghosh41/galaxy-init
    resources: {}
    volumeMounts:
    - name: shared-data
      mountPath: /export/ 
  
    ports:
    - containerPort: 80