apiVersion: v1
kind: Pod
metadata:
  name: galaxy-htcondor-executor
spec:

  volumes:
  - name: shared-data
    persistentVolumeClaim:
     claimName: shared-data
     
  - persistentVolumeClaim:
     claimName: dockersocket
    name: dockersocket
  containers:
  
  - name: galaxy-htcondor-executor
    image: abhikghosh41/galaxy-htcondor-executor
    resources: {}
    volumeMounts:
    - name: shared-data
      mountPath: /export/ 
    - name: dockersocket
      mountPath: /var/run/docker.sock    
    securityContext:
          privileged: true
  
    ports:
    - containerPort: 80