apiVersion: v1
kind: Pod
metadata:
  name: galaxy-slurm
spec:

  volumes:
  - name: shared-data
    persistentVolumeClaim:
     claimName: shared-data
     
  - persistentVolumeClaim:
     claimName: dockersocket
    name: dockersocket
  containers:
  
  - name: galaxy-slurm
    image: abhikghosh41/galaxy-slurm
    
    resources: {}
    volumeMounts:
    - name: shared-data
      mountPath: /export/  
    ports:
    - containerPort: 80
  