apiVersion: v1
kind: Pod
metadata:
  name: galaxy-rabbitmq
spec:

  volumes:
  - name: shared-data
    persistentVolumeClaim:
     claimName: shared-data
     

  containers:
  
  - name:  galaxy-rabbitmq
    image: rabbitmq:alpine
    volumeMounts:
    - name: shared-data
      mountPath: /var/lib/rabbitmq    
    env: 
    - name: RABBITMQ_DEFAULT_USER
      value: galaxy
    - name: RABBITMQ_DEFAULT_PASS
      value: vaiJa3ieghai2ief0jao
    - name: RABBITMQ_DEFAULT_VHOST
      value: galaxy
  
    ports:
    - containerPort: 80
  