apiVersion: v1
kind: Pod
metadata:
  name: galaxy-init
spec:

  volumes:
  - name: shared-data
    persistentVolumeClaim:
     claimName: shared-data
    
  - persistentVolumeClaim:
     claimName: dockersocket
    name: dockersocket
  securityContext:

     fsGroup: 1234 
  
  containers:
    
  - name: galaxy-init
    image: abhikghosh41/galaxykansals-init
    resources: {}
    volumeMounts:
    - name: shared-data
      mountPath: /export:z 
  
    ports:
    - containerPort: 80
    
    securityContext:
          privileged: true
          runAsUser: 0