apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockersocket
spec:
  capacity:
    storage: 1Gi 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  nfs: 
    path: /var/run/docker.sock 
    server: nfs.f22 
    readOnly: false