apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-galaxy-initdb
  labels:
    app.kubernetes.io/name: {{ include "galaxy.name" . }}
    helm.sh/chart: {{ include "galaxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- $root := . }}
  {{ range $path, $bytes := .Files.Glob "files/conf.d/*" }}
    {{- base $path }}: {{ $root.Files.Get $path | quote }}
  {{ end }}
